using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Linq;
using System.Text;

namespace SimpleStorage.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class BinarySerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: (ctx, cancellationToken) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
                    var semanticModel = ctx.SemanticModel;
                    if (semanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not INamedTypeSymbol classSymbol)
                    {
                        return null;
                    }

                    foreach (var attr in classSymbol.GetAttributes())
                    {
                        var name = attr.AttributeClass.Name;
                        var attrName = attr.AttributeClass?.ToDisplayString();

                        if (name == "GenerateBinarySerializerAttribute" ||
                            attrName?.EndsWith("GenerateBinarySerializerAttribute", StringComparison.InvariantCulture) == true)
                        {
                            return classSymbol;
                        }
                    }

                    return null;
                })
            .Where(symbol => symbol is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(
            compilationAndClasses,
            (ctx, combined) =>
            {
                var (compilation, symbols) = combined;
                foreach (var symbol in symbols)
                {
                    if (symbol is INamedTypeSymbol classSymbol)
                    {
                        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
                        var code = GenerateSerializerCode(classSymbol, namespaceName);
                        ctx.AddSource($"{classSymbol.Name}_BinarySerializer.g.cs", code);
                    }
                }
            });
    }

    private static string GenerateSerializerCode(INamedTypeSymbol classSymbol, string namespaceName)
    {
        var className = classSymbol.Name;

        var properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .ToList();

        var stringBuilder = new StringBuilder($@"// <auto-generated />
using System;
using System.IO;
using System.Text;

namespace {namespaceName}
{{
    public partial class {className}
    {{
        public void SerializeToBinary(Stream stream)
        {{
            using var writer = new BinaryWriter(stream, Encoding.UTF8, leaveOpen: true);
");

        foreach (var prop in properties)
        {
            var name = prop.Name;
            var type = prop.Type.ToDisplayString();
            switch (type)
            {
                case "int":
                    stringBuilder.AppendLine($"            writer.Write({name});");
                    break;
                case "string":
                    stringBuilder.AppendLine($"            writer.Write({name});");
                    break;
                case "System.DateTime":
                    stringBuilder.AppendLine($"            writer.Write({name}.Ticks);");
                    break;
                default:
                    stringBuilder.AppendLine($"            // TODO: сериализация {type} для свойства {name}");
                    break;
            }
        }

        stringBuilder.AppendLine($@"        }}

        public static {className} DeserializeFromBinary(Stream stream)
        {{
            var obj = new {className}();
            using var reader = new BinaryReader(stream);
");

        foreach (var prop in properties)
        {
            var name = prop.Name;
            var type = prop.Type.ToDisplayString();

            switch (type)
            {
                case "int":
                    stringBuilder.AppendLine($"            obj.{name} = reader.ReadInt32();");
                    break;
                case "string":
                    stringBuilder.AppendLine($"            obj.{name} = reader.ReadString();");
                    break;
                case "System.DateTime":
                    stringBuilder.AppendLine($"            obj.{name} = new DateTime(reader.ReadInt64());");
                    break;
                default:
                    stringBuilder.AppendLine($"            // TODO: десериализация {type} для свойства {name}");
                    break;
            }
        }

        stringBuilder.AppendLine($@"
            return obj;
        }}
    }}
}}");
        return stringBuilder.ToString();
    }
}